Awesome books: refactor to use JavaScript classes
ForHemer/Awesome-book pull request #2
Opened 2022-02-08 20:17 UTC by craigs40

In this project, we will refactor the Awesome books application to use JavaScript classes.

2022-02-08 21:41 UTC, Lameck1 requested changes
Hi, @craigs40 & @ForHemer, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-08 21:41 UTC, Lameck1 commented on index.js
>    const bookTitle = document.querySelector('#title').value;
- [ ] According to this requirement 👇🏿:

  > - Create class methods to add and remove books.

  The methods for adding and removing books should be class methods. So, you ought to have refactored them into the class. Please ensure the `addBook` method is a class method.

2022-02-08 21:41 UTC, Lameck1 commented on index.js
>    if (books.length === 1) {
- [ ] Same issue as above. Please ensure that the `deleteBook` method is moved into the class to make it a class method.

2022-02-09 15:12 UTC, Deepakdanger approved these changes
**Hi @team,** 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-09 15:18 UTC, merged